name: 2.2.x branch

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim-version:
          - 2.2.2
          - 2.2.0

    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 2.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install the builder-pusher app
        run: nimble install dhbp@">=1.0.3"

      - name: Set up multiarch builder
        run: dhbp setup

      - name: Build and push the image
        run: dhbp build-and-push ${{ matrix.nim-version }}

